[WIP] Build: test on JDK 8, 9 & 10 (skip 11)
kirasystems/saml20-clj pull request #9
Opened 2019-06-24 22:55 UTC by jlebedeva

This change makes the project build do 3 runs using JDK 8, 9 and 10 instead of running on default which is JDK 11.

After the latest merge the TravisCI build shows red. The best guess is that between last time the PR was built – an unreasonable time of 3 months ago – and it was merged TravisCI has changed defaults for JDK-based project to use JDK 11 instead of JDK 8. The project was not ready and the build is failing on JDK 11.

Note: I am moderately convinced we should run on a few different JDK versions, and this PR is then required. The build is failing at the moment though: it fails on JDK 9 and 10 due to missing JAXB dependency that is no longer provided with 9/10 (which may or may not be affecting your application).

2019-06-24 23:56 UTC, jlebedeva commented
Since the project now builds on JDK 11 which was not the original goal (I've been fixing the red build here) I've updated the description, the title and the commits. I think I might as well have re-opened this PR but I grew attached to it. If you see
- multiple changes in this PR
- additional cleanup commit

as not a good practice I am happy to fix it. Anything for the reviewers =)

2019-06-25 14:14 UTC, zmingxie approved these changes
LGTM 👍

2019-06-25 14:15 UTC, MatthewDarling requested changes
I'm a little bit concerned about the alphabetical dep sorting, since it affects transitive dependency resolution. Diffing the `lein deps :tree` between this branch and `dev`, luckily there's only one difference: we get `ring/ring-core` transitively from `compojure`, rather than from the top-level `ring`. And, even more luckily, it's the same version - `1.4.0`.

But now upgrading `ring` wouldn't actually affect the version we're using, or upgrading `compojure` would make our `ring-devel` dep get out of sync with `ring-core`.

So, I think we should move `ring` above `compojure` at least.

2019-06-25 14:22 UTC, jlebedeva commented
If my memory doesn't fault me when you specify a direct dependency it always overrides the transitive one regardless on the order. Is there a way I can see that it is not true?

2019-06-25 14:28 UTC, jlebedeva commented
I see what you are saying. Dependency `ring/ring-core` is a transitive one (never direct) and it is deduplicated once it is already on the classpath. I believe the correct move is to add exclusions rather than reorder dependencies. If ring version changes and one would not be `1.4.0` anymore we would be getting a warning from `:pedantic :warn` in our `project.clj`.

2019-06-25 14:29 UTC, MatthewDarling commented
Oh, that fits with what I saw actually - I thought I'd see Clojure 1.7 on this branch due to `clj-time 0.11`, but it showed 1.8.

What I did to check the transitive deps was:

```
➜  saml20-clj git:(dev) ✗ lein with-profile -dev deps :tree > old-deps.edn
➜  saml20-clj git:(dev) ✗ git checkout travis-jdks
➜  saml20-clj git:(travis-jdks) ✗ lein with-profile -dev deps :tree > new-deps.edn
➜  saml20-clj git:(travis-jdks) ✗ diff old-deps.edn new-deps.edn --context=6
*** old-deps.edn	2019-06-25 10:14:04.000000000 -0400
--- new-deps.edn	2019-06-25 10:13:49.000000000 -0400
***************
*** 4,15 ****
--- 4,21 ----
   [compojure "1.5.0"]
     [clout "2.1.2"]
       [instaparse "1.4.0" :exclusions [[org.clojure/clojure]]]
     [medley "0.7.3"]
     [org.clojure/tools.macro "0.1.5"]
     [ring/ring-codec "1.0.0"]
+    [ring/ring-core "1.4.0"]
+      [commons-fileupload "1.3.1"]
+      [commons-io "2.4"]
+      [crypto-equality "1.0.0"]
+      [crypto-random "1.2.0"]
+      [org.clojure/tools.reader "0.9.1"]
   [nrepl "0.6.0" :exclusions [[org.clojure/clojure]]]
   [org.apache.santuario/xmlsec "2.0.4"]
     [commons-codec "1.10"]
     [org.codehaus.woodstox/woodstox-core-asl "4.4.1"]
       [javax.xml.stream/stax-api "1.0-2"]
       [org.codehaus.woodstox/stax2-api "3.1.4"]
***************
*** 30,47 ****
     [org.owasp.esapi/esapi "2.0.1" :exclusions [[commons-configuration] [commons-beanutils/commons-beanutils-core] [commons-fileupload] [commons-io] [commons-collections] [log4j] [xom] [org.beanshell/bsh-core] [org.owasp.antisamy/antisamy]]]
   [org.vlacs/helmsman "1.0.0-alpha5"]
     [com.taoensso/timbre "4.1.4" :exclusions [[org.clojure/tools.reader]]]
       [com.taoensso/encore "2.18.0"]
       [io.aviso/pretty "0.1.17"]
   [ring "1.4.0"]
-    [ring/ring-core "1.4.0"]
-      [commons-fileupload "1.3.1"]
-      [commons-io "2.4"]
-      [crypto-equality "1.0.0"]
-      [crypto-random "1.2.0"]
-      [org.clojure/tools.reader "0.9.1"]
     [ring/ring-devel "1.4.0"]
       [clj-stacktrace "0.2.8"]
       [hiccup "1.0.5"]
       [ns-tracker "0.3.0"]
         [org.clojure/java.classpath "0.2.2"]
         [org.clojure/tools.namespace "0.2.10"]
--- 36,47 ----
```

So, in the new file, `ring-core` is removed from below `ring` and added below `compojure`.

2019-06-25 14:37 UTC, jlebedeva commented
Oh 🤣 I called `project.clj` `project.xml`. Ouch. I'll change the messages while no one's looking.

2019-06-25 14:42 UTC, jlebedeva commented
Gotta be be good finally - please take a look.
@MatthewDarling thank you, it is useful to learn that order of dependency declarations has a tangible effect. I was not properly aware of that.

2019-06-25 14:44 UTC, MatthewDarling approved these changes
Looks good now, exclusion is definitely nicer than moving things around and leaving comments saying "don't touch this!" 👍

2019-06-25 15:00 UTC, merged